name: E2E Playwright Tests
on:
  # push:
  #   branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./e2e
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install playwright with dependencies
      run: yarn install
    - name: Run Playwright tests
      run: yarn test
    - uses: microsoft/playwright-github-action@v1
